/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetos.sistema_funcionario.view;

import javax.swing.JButton;

/**
 *
 * @author Gabriel Namã
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaManterFuncionario
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelManterFuncionario = new javax.swing.JPanel();
        tituloJanela = new javax.swing.JLabel();
        labelBoasVindas = new javax.swing.JLabel();
        labelFuncionario = new javax.swing.JLabel();
        labelSalarios = new javax.swing.JLabel();
        botaoAcessarFuncionarios = new javax.swing.JButton();
        botaoAcessarSalarios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manter funcionários");

        tituloJanela.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tituloJanela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloJanela.setText("SISTEMA DE FUNCIONÁRIOS");

        labelBoasVindas.setText("Bem-vindo!");

        labelFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelFuncionario.setText("Funcionários:");

        labelSalarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelSalarios.setText("Salários:");

        botaoAcessarFuncionarios.setText("Acessar");

        botaoAcessarSalarios.setText("Acessar");

        jLabel1.setText("Versão do compilador: 11");

        jLabel2.setText("Arquivo de log: FuncionarioLog.log");

        jLabel3.setText("Arquivo de persistência de dados: Arquivo.txt");

        javax.swing.GroupLayout painelManterFuncionarioLayout = new javax.swing.GroupLayout(painelManterFuncionario);
        painelManterFuncionario.setLayout(painelManterFuncionarioLayout);
        painelManterFuncionarioLayout.setHorizontalGroup(
            painelManterFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelManterFuncionarioLayout.createSequentialGroup()
                .addGroup(painelManterFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelManterFuncionarioLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelBoasVindas)
                        .addGap(115, 115, 115))
                    .addGroup(painelManterFuncionarioLayout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addGroup(painelManterFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoAcessarFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(146, 146, 146)
                        .addGroup(painelManterFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoAcessarSalarios)
                            .addComponent(labelSalarios))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addGap(0, 291, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelManterFuncionarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelManterFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelManterFuncionarioLayout.createSequentialGroup()
                        .addGroup(painelManterFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelManterFuncionarioLayout.createSequentialGroup()
                        .addComponent(tituloJanela)
                        .addGap(346, 346, 346))))
        );
        painelManterFuncionarioLayout.setVerticalGroup(
            painelManterFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelManterFuncionarioLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(tituloJanela)
                .addGap(48, 48, 48)
                .addComponent(labelBoasVindas)
                .addGap(71, 71, 71)
                .addGroup(painelManterFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFuncionario)
                    .addComponent(labelSalarios))
                .addGap(30, 30, 30)
                .addGroup(painelManterFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAcessarFuncionarios)
                    .addComponent(botaoAcessarSalarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(painelManterFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(painelManterFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    
    public JButton getBotaoAcessarFuncionarios() {
        return botaoAcessarFuncionarios;
    }
    
    public JButton getBotaoAcessarSalarios() {
        return botaoAcessarSalarios;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAcessarFuncionarios;
    private javax.swing.JButton botaoAcessarSalarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelBoasVindas;
    private javax.swing.JLabel labelFuncionario;
    private javax.swing.JLabel labelSalarios;
    private javax.swing.JPanel painelManterFuncionario;
    private javax.swing.JLabel tituloJanela;
    // End of variables declaration//GEN-END:variables
}
