/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetos.sistema_funcionario.view;

import javax.swing.JButton;

/**
 *
 * @author Gabriel Namã
 */
public class TelaManterFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form TelaManterFuncionario
     */
    public TelaManterFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelManterFuncionario = new javax.swing.JPanel();
        tituloJanela = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelIdade = new javax.swing.JLabel();
        labelCargo = new javax.swing.JLabel();
        jNome = new javax.swing.JTextField();
        jIdade = new javax.swing.JTextField();
        jCargo = new javax.swing.JComboBox<>();
        jSalvar = new javax.swing.JButton();
        jCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSalario = new javax.swing.JTextField();
        isGeneroso = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manter funcionários");

        tituloJanela.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tituloJanela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloJanela.setText("CADASTRO DE FUNCIONÁRIOS");

        labelNome.setText("Nome:");

        labelIdade.setText("Idade:");

        labelCargo.setText("Cargo:");

        jNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomeActionPerformed(evt);
            }
        });

        jCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estagiário", "Programador", "Analista", "Gerente de Projetos" }));

        jSalvar.setText("Salvar");

        jCancelar.setText("Fechar");

        jLabel1.setText("Salário: R$");

        jSalario.setText(" ");

        isGeneroso.setText("Bônus generoso");

        javax.swing.GroupLayout painelManterFuncionarioLayout = new javax.swing.GroupLayout(painelManterFuncionario);
        painelManterFuncionario.setLayout(painelManterFuncionarioLayout);
        painelManterFuncionarioLayout.setHorizontalGroup(
            painelManterFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelManterFuncionarioLayout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addGroup(painelManterFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelManterFuncionarioLayout.createSequentialGroup()
                        .addComponent(tituloJanela)
                        .addGap(324, 324, 324))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelManterFuncionarioLayout.createSequentialGroup()
                        .addGroup(painelManterFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painelManterFuncionarioLayout.createSequentialGroup()
                                .addComponent(labelNome)
                                .addGap(18, 18, 18)
                                .addComponent(jNome))
                            .addGroup(painelManterFuncionarioLayout.createSequentialGroup()
                                .addComponent(labelIdade)
                                .addGap(21, 21, 21)
                                .addComponent(jIdade))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelManterFuncionarioLayout.createSequentialGroup()
                                .addGroup(painelManterFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(painelManterFuncionarioLayout.createSequentialGroup()
                                        .addComponent(labelCargo)
                                        .addGap(18, 18, 18)
                                        .addGroup(painelManterFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(isGeneroso, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jCancelar))
                                .addGroup(painelManterFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelManterFuncionarioLayout.createSequentialGroup()
                                        .addGap(113, 113, 113)
                                        .addComponent(jSalvar))
                                    .addGroup(painelManterFuncionarioLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(170, 170, 170))))
        );
        painelManterFuncionarioLayout.setVerticalGroup(
            painelManterFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelManterFuncionarioLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(tituloJanela)
                .addGap(59, 59, 59)
                .addGroup(painelManterFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(jNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelManterFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdade)
                    .addComponent(jIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(painelManterFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCargo)
                    .addComponent(jCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(isGeneroso)
                .addGap(18, 18, 18)
                .addGroup(painelManterFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCancelar)
                    .addComponent(jSalvar))
                .addContainerGap(259, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(painelManterFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(painelManterFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNomeActionPerformed

    private void jIdadeActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void jSalvarActionPerformed(java.awt.event.ActionEvent evt) {                                        
    }                                       

    private void isGenerosoActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    public JButton getSalvar() {
        return jSalvar;
    }
    
    public JButton getCancelar() {
        return jCancelar;
    }
    
    public String getNome() {
        return jNome.getText();
    }
    
    public String getCargo() {
        return jCargo.getSelectedItem().toString();
    }
    
    public int getIdade() {
        return Integer.parseInt(jIdade.getText());
    }
    
    public double getSalario() {
        return Double.parseDouble(jSalario.getText());
    }
    
    public String getTipoBonus() {
        if (isGeneroso.isSelected()) {
            return "generoso";
        } else {
            return "normal";
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox isGeneroso;
    private javax.swing.JButton jCancelar;
    private javax.swing.JComboBox<String> jCargo;
    private javax.swing.JTextField jIdade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jNome;
    private javax.swing.JTextField jSalario;
    private javax.swing.JButton jSalvar;
    private javax.swing.JLabel labelCargo;
    private javax.swing.JLabel labelIdade;
    private javax.swing.JLabel labelNome;
    private javax.swing.JPanel painelManterFuncionario;
    private javax.swing.JLabel tituloJanela;
    // End of variables declaration//GEN-END:variables
}
